
function getquestiOneInput(){
    answertwo = document.getElementById("getquestionOneInput").ariaValueMax;

    console.log(answerone)

}


function getquestiTwoInput(){
    answertwo = document.getElementById("getquestioTwoInput").ariaValueMax;
    
    console.log(answertwo)
    
}

function getquestiThreeInput(){
    answerthree = document.getElementById("getquestioThreeInput").ariaValueMax;
        
    console.log(answerthree)
        
}   
 
function getquestiFourInput(){
    answerfour = document.getElementById("getquestioFourInput").ariaValueMax;

    console.log(answerfour)
}



function getquestiFiveInput(){
    answerfive = document.getElementById("getquestioFiveInput").ariaValueMax;
    
    console.log(answerfive)
    }